create schema if not exists atherysquests;

create table atherysquests.attempted_quest (
    id bigint generated by default as identity,
    first_timestamp bigint,
    questId varchar(255),
    times_completed integer,
    timestamp bigint,
    primary key (id)
);

create table atherysquests.Quester_ongoingQuests (
    SimpleQuester_id binary not null,
    ongoingQuests text
);

create table atherysquests.QuestLocation (
    id bigint generated by default as identity,
    location varchar(255),
    questId varchar(255),
    radius double not null,
    type integer,
    primary key (id)
);

create table atherysquests.SimpleQuester (id binary not null, primary key (id));

